services:
  interasisai-web:
    container_name: interasisai-web
    build:
      context: ./interasisai-web # Aponta para a subpasta do Next.js
      dockerfile: Dockerfile
      args:
        # COMENTÁRIO: O Compose lê os valores injetados pelo comando no terminal
        - NEXT_PUBLIC_PYTHON_BACKEND_URL
        - NEXT_PUBLIC_TENANT_ID
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./interasisai-web/.env
    networks:
      - proxy_default

  chatatendimento-api:
    build:
      context: ./atendimento-ia
      dockerfile: Dockerfile
    container_name: chatatendimento-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8001:8000"
    extra_hosts:
      # COMENTÁRIO: Permite que o container acesse serviços rodando no Host via 'host.docker.internal'
      - "host.docker.internal:host-gateway"
    env_file:
      - ./atendimento-ia/.env
    networks:
      - proxy_default
      
  networks:
   proxy_default:
    name: simplificandoai_default # Garanta que bate com o nome exato da rede do Nginx Proxy Manager
    external: true